### ISSUE TITLE
Skicka vidare felmeddelanden från andra tjänster bättre

### ISSUE THREAD

**Issue by hnrklssn** [Dsek-LTH/gateway#11]
Svar direkt från hoarDer:
```
{
  "errors": [
    {
      "message": "request not authenticated",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "checkOutUnit"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED",
        "exception": {
          "stacktrace": [
            "AuthenticationError: request not authenticated",
            "    at checkOutUnit (/usr/src/app/dist/main.js:308:23)",
            "    at /usr/src/app/node_modules/graphql-tools/dist/makeExecutableSchema.js:64:22",
            "    at field.resolve (/usr/src/app/node_modules/apollo-server-express/node_modules/graphql-extensions/dist/index.js:133:26)",
            "    at resolveFieldValueOrError (/usr/src/app/node_modules/graphql/execution/execute.js:467:18)",
            "    at resolveField (/usr/src/app/node_modules/graphql/execution/execute.js:434:16)",
            "    at /usr/src/app/node_modules/graphql/execution/execute.js:244:18",
            "    at /usr/src/app/node_modules/graphql/jsutils/promiseReduce.js:23:10",
            "    at Array.reduce (<anonymous>)",
            "    at promiseReduce (/usr/src/app/node_modules/graphql/jsutils/promiseReduce.js:20:17)",
            "    at executeFieldsSerially (/usr/src/app/node_modules/graphql/execution/execute.js:241:37)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

Svar om query görs via gateway:
```
{
  "errors": [
    {
      "message": "[object Object]",
      "locations": [
        {
          "line": 39,
          "column": 11
        }
      ],
      "path": [
        "checkOutUnit"
      ]
    }
  ],
  "data": null
}
```

**Comment by hnrklssn** [comment]
Kanske löser sig själv om man går vidare med #10

**Comment by hnrklssn** [comment]
Woops var redan täckt i #7
